-- Project 1: Julieta Abdon: An Artistic Vision
INSERT INTO projects (
    project_id,
    project_name,
    project_logo_1,
    project_logo_2,
    project_description,
    project_overview_description_part_01,
    project_overview_description_part_02,
    project_overview_main_media_type,
    project_overview_technologies,
    project_overview_duration,
    project_timeline_event_01_title,
    project_timeline_event_01,
    project_timeline_event_02_title,
    project_timeline_event_02,
    project_timeline_event_03_title,
    project_timeline_event_03,
    project_timeline_event_04_title,
    project_timeline_event_04,
    project_timeline_event_05_title,
    project_timeline_event_05,
    project_final_results_description_part_01,
    project_final_results_description_part_02,
    project_final_results_stat_01_title,
    project_final_results_stat_01,
    project_final_results_stat_02_title,
    project_final_results_stat_02,
    project_final_results_stat_03_title,
    project_final_results_stat_03,
    project_external_url
) VALUES (
    1,
    'Julieta Abdon: An Artistic Vision',
    NULL,
    NULL,
    'Julieta wanted a website that would showcase her works, values, and personal brand with clarity. The goal was a site that felt simple to navigate while still communicating creativity and credibility as an artist, with a clear, elegant presence today.',
    'The final result goes beyond a personal brand website. It gives Julieta a platform to express herself, connect with clients, grow her network, and strengthen her presence online through a focused, practical solution built for lasting growth at scale.',
    'Building the site was a lesson in problem-solving, from learning Elementor to creating a responsive, accessible experience for the first time. Across three months, I focused on usability and performance to deliver clean, accessible results for Belen.',
    'images',
    'JavaScript, PHP, MySQL, HTML, CSS',
    '3 months',
    'Start',
    'Initial layout in Elementor; built with docs and community help.',
    'Text and images',
    'Added texts and images; standardized on WebP for performance.',
    'Development',
    'Implemented animations and clear navigation focused on CTAs.',
    'Design eye',
    'Made site responsive and accessible for inclusive, device-wide UX.',
    'Finish',
    'Monitored impact; supported bugs and edge cases post-launch.',
    'The successful launch of Julieta''s website was a significant event. She was delighted with the final solution and continues to use it on a daily basis to connect with her clients and expand her professional network.',
    'Just a month later, she reported an increase of site total visits of 13% MoM, and an increase on the conversion rate of 2% YoY.',
    'Site total visits MoM',
    '+13% MoM site total visits',
    'Sales conversion rate YoY',
    '+2% YoY sales conversion rate',
    NULL,
    NULL,
    'https://julietaabdon.com/'
);

-- Project 2: ABV: Design in Motion
INSERT INTO projects (
    project_id,
    project_name,
    project_logo_1,
    project_logo_2,
    project_description,
    project_overview_description_part_01,
    project_overview_description_part_02,
    project_overview_main_media_type,
    project_overview_technologies,
    project_overview_duration,
    project_timeline_event_01_title,
    project_timeline_event_01,
    project_timeline_event_02_title,
    project_timeline_event_02,
    project_timeline_event_03_title,
    project_timeline_event_03,
    project_timeline_event_04_title,
    project_timeline_event_04,
    project_timeline_event_05_title,
    project_timeline_event_05,
    project_final_results_description_part_01,
    project_final_results_description_part_02,
    project_final_results_stat_01_title,
    project_final_results_stat_01,
    project_final_results_stat_02_title,
    project_final_results_stat_02,
    project_final_results_stat_03_title,
    project_final_results_stat_03,
    project_external_url
) VALUES (
    2,
    'ABV: Design in Motion',
    NULL,
    NULL,
    'Belen needed a portfolio site that went beyond expectations and reflected her unconventional design vision. It became a visual experience that showcased architectural work, expressed her creative approach, and turned into a talking point among peers.',
    'The project was more than a portfolio: it reflected Belen''s design philosophy and challenged me to deliver a unique, interactive experience with beauty and technical solidity that felt intentional from the very first glance and every detail mattered.',
    'The site opens with a seamless gallery flow, where motion feels natural and carefully composed. Built with JavaScript, Linux, and supporting technologies, it blended motion, server robustness, and elegance, turning a gallery into an immersive journey.',
    'images',
    'JavaScript, MariaDB, HTML, CSS',
    '2 months',
    'Init',
    'Initialized repo; provisioned DigitalOcean droplet.',
    'Text and images',
    'Curated content; adapted assets to the custom carousel.',
    'Server',
    'Hardened server; followed CIS benchmarks on Linux.',
    'Last touch',
    'Ensured complex layout works across sizes; aligned with WCAG.',
    'Launch & post-launch',
    'Tested in prod-like environments; provided extended support.',
    'The client''s enthusiastic response to the final website was really gratifying. Belen adopted the website as her primary portfolio.',
    'Within a month of its release, total visits rose up to 20% MoM and the website was featured in a prominent Spanish architectural blog for its outstanding design.',
    'Site total visits MoM',
    '+20% MoM site total visits',
    'Press feature',
    'Site featured on Dazeen',
    NULL,
    NULL,
    'https://bvarchitecture.es/'
);

-- Project 3: En Marte: From Another Planet
INSERT INTO projects (
    project_id,
    project_name,
    project_logo_1,
    project_logo_2,
    project_description,
    project_overview_description_part_01,
    project_overview_description_part_02,
    project_overview_main_media_type,
    project_overview_technologies,
    project_overview_duration,
    project_timeline_event_01_title,
    project_timeline_event_01,
    project_timeline_event_02_title,
    project_timeline_event_02,
    project_timeline_event_03_title,
    project_timeline_event_03,
    project_timeline_event_04_title,
    project_timeline_event_04,
    project_timeline_event_05_title,
    project_timeline_event_05,
    project_final_results_description_part_01,
    project_final_results_description_part_02,
    project_final_results_stat_01_title,
    project_final_results_stat_01,
    project_final_results_stat_02_title,
    project_final_results_stat_02,
    project_final_results_stat_03_title,
    project_final_results_stat_03,
    project_external_url
) VALUES (
    3,
    'En Marte: From Another Planet',
    NULL,
    NULL,
    'EN MARTE was designed to do more than sell. It balanced a laid-back aesthetic with a seamless shopping experience, intuitive UX, and a clear path to purchase. The result exceeded expectations, lifting conversion and becoming a talking point in Spain.',
    'EN MARTE took me back to my CX director years, when memorable journeys mattered most. The challenge was to balance Camila''s laid-back brand with a clear path to purchase, making products easy to browse and easy to shop, making the path feel natural.',
    'Working within Shopify''s Liquid framework meant adapting design and logic to the platform''s constraints. The result became Camila''s main sales channel, delivering a 17.4% YoY sales increase and a 4% MoM conversion boost for Camila and her customers.',
    'images',
    'Liquid, JavaScript, MySQL, HTML, CSS',
    '3 months',
    'Site config',
    'Implemented Shopify setup, payments, and Liquid best practices.',
    'Database seeding',
    'Created products and categories; structured collections.',
    'Fine-tuning',
    'Refined layouts, navigation, and header logic to boost conversion.',
    'Feedback loop',
    'Applied client feedback; shifted aesthetics to a laid-back style.',
    'Results',
    'Evaluated impact; supported issues and edge cases post-launch.',
    'The culmination of this project is an online store that not only empowers Camila to sell across Europe but also delivers measurable growth.',
    'Just months after launch, sales increased 17.4% year-over-year, with a 4% month-over-month boost in conversion. These results validate the design decisions, proving that a well designed and easy to use UX directly translates into business results.',
    'Total sales YoY',
    '+17.4% YoY total sales increase',
    'Sales conversion rate MoM',
    '+4% MoM sales conversion rate',
    'Sales channels expansion',
    'Instagram-only to multi-sales-channel',
    'https://enmarte.shop/'
);

-- Project 4: ISSAS: Alla Italiana
INSERT INTO projects (
    project_id,
    project_name,
    project_logo_1,
    project_logo_2,
    project_description,
    project_overview_description_part_01,
    project_overview_description_part_02,
    project_overview_main_media_type,
    project_overview_technologies,
    project_overview_duration,
    project_timeline_event_01_title,
    project_timeline_event_01,
    project_timeline_event_02_title,
    project_timeline_event_02,
    project_timeline_event_03_title,
    project_timeline_event_03,
    project_timeline_event_04_title,
    project_timeline_event_04,
    project_timeline_event_05_title,
    project_timeline_event_05,
    project_final_results_description_part_01,
    project_final_results_description_part_02,
    project_final_results_stat_01_title,
    project_final_results_stat_01,
    project_final_results_stat_02_title,
    project_final_results_stat_02,
    project_final_results_stat_03_title,
    project_final_results_stat_03,
    project_external_url
) VALUES (
    4,
    'ISSAS: Alla Italiana',
    NULL,
    NULL,
    'Developed a modern e-commerce site for ISSAS, a luxury jewelry brand in Copenhagen, translating Monica''s style into a refined digital experience built for international growth.',
    'The site paired an Italian-inspired minimalist aesthetic with a high-impact hero video, product-led CTAs, and intuitive navigation to create a polished shopping experience.',
    'Built with Shopify CLI, Git/GitHub, WebP optimization, and accessibility-first practices, the project delivered a 95+ Lighthouse score, a 10% MoM sales lift, and first orders from Sweden, Germany, and the Netherlands.',
    'images',
    'Liquid, JavaScript, MySQL, HTML, CSS',
    '2 months',
    'Platform''s config',
    'Granted dev access; set up domain DNS.',
    'Development process',
    'Built dev/prod envs, seeded DB, translated sketches to code.',
    'Feedback',
    'Iterated with client; improved layout and CTA sections.',
    'Fine-tuning',
    'Polished visuals; optimized images for intended impact.',
    'Results',
    'Monitored results; provided support for bugs and edge cases.',
    'A 10% MoM total sales increase and international market expansion allowing the client to sell her products in Sweden, Germany and The Netherlands.',
    'Despite the dynamic nature of the project and the client''s adjustments, the final result was a source of mutual satisfaction. The successful collaboration on this project laid the foundation for future collaborations, demonstrating the value of open communication and a shared commitment to achieving the client''s vision.',
    'Total sales MoM',
    '+10% MoM total sales increase',
    'International orders',
    'Cross-borders orders from SE, DE and NL',
    NULL,
    NULL,
    'https://issasjewelry.com/'
);

-- Project 5: P-E-M: Breaking the Chains
INSERT INTO projects (
    project_id,
    project_name,
    project_logo_1,
    project_logo_2,
    project_description,
    project_overview_description_part_01,
    project_overview_description_part_02,
    project_overview_main_media_type,
    project_overview_technologies,
    project_overview_duration,
    project_timeline_event_01_title,
    project_timeline_event_01,
    project_timeline_event_02_title,
    project_timeline_event_02,
    project_timeline_event_03_title,
    project_timeline_event_03,
    project_timeline_event_04_title,
    project_timeline_event_04,
    project_timeline_event_05_title,
    project_timeline_event_05,
    project_final_results_description_part_01,
    project_final_results_description_part_02,
    project_final_results_stat_01_title,
    project_final_results_stat_01,
    project_final_results_stat_02_title,
    project_final_results_stat_02,
    project_final_results_stat_03_title,
    project_final_results_stat_03,
    project_external_url
) VALUES (
    5,
    'P-E-M: Breaking the Chains',
    NULL,
    NULL,
    'Rebuilt and migrated Proyecto en Madera''s corporate site, replacing a restrictive Bitrix setup with a modern WordPress solution that gave the team full control over content updates and a cleaner path for future growth.',
    'The rebuild included a custom theme, Docker-based development, and a hardened Ubuntu deployment with WordPress, MariaDB, and Nginx, plus HTTPS, server hardening, and a secure production workflow.',
    'Since launch, P-E-M cut operating costs by up to 95%, enabled same-day edits, and supported new export channels in China and the United States while site visits and organic traffic continued to rise.',
    'images',
    'Liquid, JavaScript, MySQL, HTML, CSS',
    '2 months',
    'Discovery & Planning',
    'Migrated from Bitrix to WordPress with goals of flexibility and cost.',
    'Theme Development',
    'Built custom theme enabling same-day edits to style and content.',
    'Infrastructure Setup',
    'Local Docker; deployed WordPress, MariaDB, and Nginx on hardened Ubuntu.',
    'Server Hardening',
    'SSH keys only, UFW, Fail2Ban, auto-updates, no root login.',
    'Launch & Results',
    'Migrated DB, enabled HTTPS, fixed redirects; traffic surged.',
    'Despite the dynamic nature of the project and the client''s adjustments, the final result was a source of mutual satisfaction.',
    'The successful collaboration on this project laid the foundation for future collaborations, demonstrating the value of open communication and a shared commitment to achieving the client''s vision.',
    'Lighthouse score',
    'Google Lighthouse score of +95%',
    'Site total visits',
    '+20% site total visits*',
    NULL,
    NULL,
    'https://www.proyectoenmadera.com.ar/'
);